[package]
name = "test_rocket_log4rs"
version = "0.1.0"
authors = ["zoumi"]

[dependencies]
rocket = "^0.3"
rocket_codegen = "^0.3" 

#env_logger = "*"
log = "0.4"
log4rs = "0.8"

[dependencies.rocket_contrib]
version = "^0.3"
default-features = false
features = ["json", "tera_templates"]