[development]
address = "0.0.0.0"
port = 8000
#workers = 8
log = "critical"
limits = { forms = 81920 }


[staging]
address = "0.0.0.0"
port = 80
#workers = 8
log = "critical"

limits = { forms = 81920 }

[production]
address = "0.0.0.0"
port = 80
#workers = 8
log = "critical"
limits = { forms = 81920 }
